/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ekqumqicsrfangqaumqa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcXVtcWljc3JmYW5ncWF1bXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MjQ2MzIsImV4cCI6MjA4NjQwMDYzMn0.H4xRwyIUA0e1t9Dm2-4sP-4M_BXLWH4ArYf8UULQYj4"